version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}
      - PORT=8000
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=http://localhost:5173,https://e-zbay-front.vercel.app
      - DEFAULT_MODEL=meta-llama/Meta-Llama-3.1-8B-Instruct
      - LARGE_MODEL=meta-llama/Llama-3.3-70B-Instruct
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend 